# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.preprocessing import *
from sklearn.model_selection import *
from sklearn.metrics import *
from sklearn.impute import *

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier



---

# Importing Dataset

In [5]:
#importing the housing data
housing_data=pd.read_csv('Housing.csv')
housing_data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [6]:
#importing the heart disease data
heart_data=pd.read_csv('heart-disease-cleaned.csv')
heart_data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,diagnosis
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,1
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,57.0,0.0,4.0,140.0,241.0,0.0,0.0,123.0,1.0,0.2,2.0,0.0,7.0,1
293,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1
294,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,1
295,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,1
296,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1



---

# Classification Model on Heart Disease

**Performing EDA**

In [7]:
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        297 non-null    float64
 1   sex        297 non-null    float64
 2   cp         297 non-null    float64
 3   trestbps   297 non-null    float64
 4   chol       297 non-null    float64
 5   fbs        297 non-null    float64
 6   restecg    297 non-null    float64
 7   thalach    297 non-null    float64
 8   exang      297 non-null    float64
 9   oldpeak    297 non-null    float64
 10  slope      297 non-null    float64
 11  ca         297 non-null    float64
 12  thal       297 non-null    float64
 13  diagnosis  297 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 32.6 KB

In [8]:
heart_data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,diagnosis
count,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000
mean,54.542088,0.676768,3.158249,131.693603,247.350168,0.144781,0.996633,149.599327,0.326599,1.055556,1.602694,0.676768,4.730640,0.461279
std,9.049736,0.468500,0.964859,17.762806,51.997583,0.352474,0.994914,22.941562,0.469761,1.166123,0.618187,0.938965,1.938629,0.499340
min,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000,3.000000,0.000000
25%,48.000000,0.000000,3.000000,120.000000,211.000000,0.000000,0.000000,133.000000,0.000000,0.000000,1.000000,0.000000,3.000000,0.000000
50%,56.000000,1.000000,3.000000,130.000000,243.000000,0.000000,1.000000,153.000000,0.000000,0.800000,2.000000,0.000000,3.000000,0.000000
75%,61.000000,1.000000,4.000000,140.000000,276.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,1.000000,7.000000,1.000000
max,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000,7.000000,1.000000

In [9]:
heart_data.isnull().sum()

age          0
sex          0
cp           0
trestbps     0
chol         0
fbs          0
restecg      0
thalach      0
exang        0
oldpeak      0
slope        0
ca           0
thal         0
diagnosis    0
dtype: int64

In [10]:
heart_data.nunique()

age           41
sex            2
cp             4
trestbps      50
chol         152
fbs            2
restecg        3
thalach       91
exang          2
oldpeak       40
slope          3
ca             4
thal           3
diagnosis      2
dtype: int64

In [11]:
#checking some categorical features
print(heart_data['sex'].value_counts())
print()
print(heart_data['cp'].value_counts())
print()
print(heart_data['fbs'].value_counts())
print()
print(heart_data['restecg'].value_counts())
print()
print(heart_data['exang'].value_counts())
print()
print(heart_data['slope'].value_counts())
print()
print(heart_data['ca'].value_counts())
print()
print(heart_data['thal'].value_counts())
print()
print(heart_data['diagnosis'].value_counts())

sex
1.0    201
0.0     96
Name: count, dtype: int64

cp
4.0    142
3.0     83
2.0     49
1.0     23
Name: count, dtype: int64

fbs
0.0    254
1.0     43
Name: count, dtype: int64

restecg
0.0    147
2.0    146
1.0      4
Name: count, dtype: int64

exang
0.0    200
1.0     97
Name: count, dtype: int64

slope
1.0    139
2.0    137
3.0     21
Name: count, dtype: int64

ca
0.0    174
1.0     65
2.0     38
3.0     20
Name: count, dtype: int64

thal
3.0    164
7.0    115
6.0     18
Name: count, dtype: int64

diagnosis
0    160
1    137
Name: count, dtype: int64

**Train Test Split:**

In [12]:
#splitting target and feature variable
heart_x=heart_data.drop('diagnosis',axis=1)
heart_y=heart_data['diagnosis']
heart_x.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0

In [13]:
heart_y.head()

0    0
1    1
2    1
3    0
4    0
Name: diagnosis, dtype: int64

In [14]:
heart_xtrain, heart_xtest, heart_ytrain, heart_ytest = train_test_split(heart_x,heart_y, test_size=0.2, random_state=25)

**Feature Scaling**

In [15]:
sc= StandardScaler()

In [16]:
sc.fit(heart_xtrain)

StandardScaler()

In [17]:
#preserving the column names
heart_trainColumnNames=heart_xtrain.columns.values
heart_trainColumnNames

array(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
       'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal'], dtype=object)

In [18]:
heart_xtrain_sc= sc.fit_transform(heart_xtrain)
heart_xtrain_sc

array([[-0.39053886,  0.68705872,  0.8590296 , ..., -0.9467613 ,
        -0.70905734,  1.17454219],
       [ 1.40451974, -1.45547966, -0.19040347, ..., -0.9467613 ,
         0.37511421, -0.87982312],
       [-0.05396537,  0.68705872, -1.23983653, ..., -0.9467613 ,
         0.37511421,  1.17454219],
       ...,
       [ 1.74109323,  0.68705872, -1.23983653, ..., -0.9467613 ,
        -0.70905734, -0.87982312],
       [ 0.39479928,  0.68705872, -0.19040347, ...,  0.67919832,
        -0.70905734,  1.17454219],
       [-0.39053886,  0.68705872,  0.8590296 , ..., -0.9467613 ,
        -0.70905734, -0.87982312]])

In [19]:
heart_xtest_sc= sc.transform(heart_xtest)
heart_xtest_sc

array([[-3.90538856e-01, -1.45547966e+00, -1.90403467e-01,
        -6.48992045e-01,  8.96385438e-01, -4.16253921e-01,
         1.01491918e+00,  2.91632749e-01, -7.07106781e-01,
        -3.54852523e-01, -9.46761301e-01, -7.09057343e-01,
        -8.79823118e-01],
       [-1.66156532e-01,  6.87058723e-01,  8.59029595e-01,
        -4.80953682e-01,  6.48915587e-01, -4.16253921e-01,
        -9.97933090e-01, -2.39841849e+00,  1.41421356e+00,
         9.18013067e-01,  6.79198325e-01,  1.45928576e+00,
         1.17454219e+00],
       [-2.78347694e-01,  6.87058723e-01, -1.23983653e+00,
        -6.48992045e-01,  1.46746971e+00, -4.16253921e-01,
        -9.97933090e-01,  9.42451596e-01, -7.07106781e-01,
        -7.18528405e-01, -9.46761301e-01, -7.09057343e-01,
        -8.79823118e-01],
       [ 1.06794625e+00,  6.87058723e-01,  8.59029595e-01,
         7.51327645e-01, -6.83614378e-01, -4.16253921e-01,
         1.01491918e+00, -7.93065329e-01, -7.07106781e-01,
         9.18013067e-01,  6.79198325e-01,  1.45928576e+00,
         6.60950865e-01],
       [ 6.19181605e-01,  6.87058723e-01,  8.59029595e-01,
        -8.17030408e-01, -3.40963816e-01,  2.40237977e+00,
        -9.97933090e-01,  4.21796519e-01,  1.41421356e+00,
         3.72499243e-01, -9.46761301e-01,  1.45928576e+00,
         1.17454219e+00],
       [ 1.18013742e+00,  6.87058723e-01,  8.59029595e-01,
         1.91199769e-01,  1.15903601e-01, -4.16253921e-01,
         1.01491918e+00, -1.01000494e+00, -7.07106781e-01,
         1.64536483e+00,  6.79198325e-01,  3.75114207e-01,
         1.17454219e+00],
       [-6.14921181e-01, -1.45547966e+00,  8.59029595e-01,
        -8.88641693e-02,  4.01445737e-01, -4.16253921e-01,
        -9.97933090e-01,  5.51960288e-01, -7.07106781e-01,
        -9.00366347e-01, -9.46761301e-01, -7.09057343e-01,
        -8.79823118e-01],
       [-2.18559745e+00,  6.87058723e-01, -1.23983653e+00,
        -5.36966470e-01, -1.06433723e+00, -4.16253921e-01,
        -9.97933090e-01,  1.02922744e+00, -7.07106781e-01,
        -9.00366347e-01, -9.46761301e-01, -7.09057343e-01,
        -8.79823118e-01],
       [-5.02730019e-01,  6.87058723e-01, -1.90403467e-01,
         4.71263707e-01, -2.83855389e-01, -4.16253921e-01,
        -9.97933090e-01,  5.51960288e-01, -7.07106781e-01,
        -3.54852523e-01,  6.79198325e-01,  3.75114207e-01,
         1.17454219e+00],
       [ 1.06794625e+00,  6.87058723e-01, -1.90403467e-01,
        -3.68928107e-01,  1.16289143e+00, -4.16253921e-01,
        -9.97933090e-01, -8.36453252e-01,  1.41421356e+00,
         7.36175125e-01,  6.79198325e-01, -7.09057343e-01,
         1.17454219e+00],
       [ 5.82257931e-02,  6.87058723e-01,  8.59029595e-01,
         4.71263707e-01, -5.88433667e-01, -4.16253921e-01,
        -9.97933090e-01, -1.70421172e+00,  1.41421356e+00,
         4.19109601e+00,  2.30515795e+00, -7.09057343e-01,
         1.17454219e+00],
       [ 1.18013742e+00, -1.45547966e+00, -1.90403467e-01,
         4.71263707e-01,  3.21879481e+00,  2.40237977e+00,
         1.01491918e+00,  2.91632749e-01, -7.07106781e-01,
        -1.73014581e-01, -9.46761301e-01,  3.75114207e-01,
        -8.79823118e-01],
       [ 1.74109323e+00,  6.87058723e-01, -1.90403467e-01,
         1.59151946e+00,  4.01445737e-01, -4.16253921e-01,
        -9.97933090e-01, -1.66082379e+00,  1.41421356e+00,
         1.73628380e+00,  6.79198325e-01,  3.75114207e-01,
         1.17454219e+00],
       [ 2.82608118e-01,  6.87058723e-01, -1.90403467e-01,
         1.03139158e+00, -2.32072262e+00,  2.40237977e+00,
        -9.97933090e-01,  9.85839519e-01, -7.07106781e-01,
        -7.18528405e-01, -9.46761301e-01,  3.75114207e-01,
         1.17454219e+00],
       [-5.02730019e-01,  6.87058723e-01,  8.59029595e-01,
         6.95314857e-01, -9.12048087e-01, -4.16253921e-01,
         1.01491918e+00, -1.05339287e+00,  1.41421356e+00,
        -8.20956106e-02,  6.79198325e-01, -7.09057343e-01,
         1.17454219e+00],
       [-9.51494668e-01,  6.87058723e-01, -1.23983653e+00,
        -1.71323501e+00, -9.69156514e-01,  2.40237977e+00,
        -9.97933090e-01,  2.48244826e-01, -7.07106781e-01,
        -9.00366347e-01, -9.46761301e-01, -7.09057343e-01,
         1.17454219e+00],
       [ 1.29232858e+00,  6.87058723e-01, -1.23983653e+00,
         1.59151946e+00, -3.63855379e-02, -4.16253921e-01,
        -9.97933090e-01, -1.31372041e+00,  1.41421356e+00,
        -9.00366347e-01,  6.79198325e-01,  2.54345731e+00,
         6.60950865e-01],
       [-1.51245048e+00, -1.45547966e+00, -1.23983653e+00,
        -8.88641693e-02, -8.35903517e-01, -4.16253921e-01,
         1.01491918e+00,  9.42451596e-01, -7.07106781e-01,
         3.72499243e-01, -9.46761301e-01, -7.09057343e-01,
        -8.79823118e-01],
       [ 2.82608118e-01,  6.87058723e-01,  8.59029595e-01,
        -1.20911992e+00,  1.65783113e+00, -4.16253921e-01,
        -9.97933090e-01, -3.15798175e-01,  1.41421356e+00,
         1.82720277e+00,  6.79198325e-01,  3.75114207e-01,
         1.17454219e+00],
       [-1.66156532e-01, -1.45547966e+00,  8.59029595e-01,
         3.59238131e-01, -2.64819246e-01, -4.16253921e-01,
         1.01491918e+00,  4.21796519e-01, -7.07106781e-01,
        -9.00366347e-01, -9.46761301e-01, -7.09057343e-01,
        -8.79823118e-01],
       [ 1.85328439e+00, -1.45547966e+00,  8.59029595e-01,
        -1.09709435e+00, -1.88289135e+00, -4.16253921e-01,
        -9.97933090e-01, -1.09678079e+00, -7.07106781e-01,
         5.54337184e-01,  6.79198325e-01, -7.09057343e-01,
        -8.79823118e-01],
       [ 9.55755092e-01, -1.45547966e+00,  8.59029595e-01,
        -1.32114550e+00,  4.01445737e-01, -4.16253921e-01,
        -9.97933090e-01,  8.12287827e-01,  1.41421356e+00,
         7.36175125e-01,  6.79198325e-01,  1.45928576e+00,
        -8.79823118e-01],
       [ 3.94799280e-01,  6.87058723e-01, -1.90403467e-01,
        -1.09709435e+00, -3.40963816e-01, -4.16253921e-01,
         1.01491918e+00,  6.38736134e-01, -7.07106781e-01,
         1.37260792e+00,  6.79198325e-01,  3.75114207e-01,
         1.17454219e+00],
       [ 1.18013742e+00, -1.45547966e+00,  8.59029595e-01,
         1.03139158e+00, -4.36144528e-01, -4.16253921e-01,
         1.01491918e+00, -1.57404795e+00, -7.07106781e-01,
         8.82336002e-03,  6.79198325e-01,  2.54345731e+00,
         1.17454219e+00],
       [ 1.70416955e-01,  6.87058723e-01, -1.90403467e-01,
        -8.88641693e-02,  1.53975886e-01,  2.40237977e+00,
         1.01491918e+00, -3.59186098e-01,  1.41421356e+00,
        -3.54852523e-01,  6.79198325e-01,  3.75114207e-01,
         6.60950865e-01],
       [ 9.55755092e-01,  6.87058723e-01,  8.59029595e-01,
         4.71263707e-01, -1.15951794e+00, -4.16253921e-01,
         1.01491918e+00, -2.72410252e-01,  1.41421356e+00,
         2.73639248e+00, -9.46761301e-01,  1.45928576e+00,
         1.17454219e+00],
       [-1.66156532e-01,  6.87058723e-01,  8.59029595e-01,
         5.83289282e-01, -4.17108385e-01, -4.16253921e-01,
         1.01491918e+00, -1.70421172e+00,  1.41421356e+00,
        -9.00366347e-01, -9.46761301e-01, -7.09057343e-01,
         1.17454219e+00],
       [-6.14921181e-01,  6.87058723e-01, -1.23983653e+00,
        -8.88641693e-02,  3.44337309e-01, -4.16253921e-01,
        -9.97933090e-01,  8.99063673e-01, -7.07106781e-01,
        -3.54852523e-01, -9.46761301e-01, -7.09057343e-01,
        -8.79823118e-01],
       [-1.06368583e+00, -1.45547966e+00, -1.23983653e+00,
        -8.88641693e-02, -2.64819246e-01, -4.16253921e-01,
         1.01491918e+00,  1.07261537e+00, -7.07106781e-01,
        -3.54852523e-01,  6.79198325e-01, -7.09057343e-01,
        -8.79823118e-01],
       [-2.29778862e+00,  6.87058723e-01, -2.28926959e+00,
        -7.61017620e-01, -1.25469865e+00, -4.16253921e-01,
         1.01491918e+00,  1.02922744e+00, -7.07106781e-01,
        -9.00366347e-01, -9.46761301e-01, -7.09057343e-01,
        -8.79823118e-01],
       [-5.39653692e-02,  6.87058723e-01,  8.59029595e-01,
        -5.36966470e-01,  7.25060157e-01, -4.16253921e-01,
         1.01491918e+00, -1.48727210e+00,  1.41421356e+00,
         2.00904071e+00,  6.79198325e-01,  1.45928576e+00,
        -8.79823118e-01],
       [ 5.06990443e-01,  6.87058723e-01, -2.28926959e+00,
         1.59151946e+00,  4.77590306e-01, -4.16253921e-01,
         1.01491918e+00, -1.09678079e+00, -7.07106781e-01,
        -9.00366347e-01, -9.46761301e-01, -7.09057343e-01,
        -8.79823118e-01],
       [-7.27112343e-01, -1.45547966e+00, -1.90403467e-01,
        -8.88641693e-02,  5.15662591e-01, -4.16253921e-01,
        -9.97933090e-01, -4.89349867e-01, -7.07106781e-01,
        -7.18528405e-01, -9.46761301e-01, -7.09057343e-01,
        -8.79823118e-01],
       [-5.39653692e-02,  6.87058723e-01, -1.90403467e-01,
        -3.68928107e-01,  4.77590306e-01, -4.16253921e-01,
         1.01491918e+00,  7.46931335e-02, -7.07106781e-01,
        -4.45771493e-01,  2.30515795e+00,  3.75114207e-01,
        -8.79823118e-01],
       [-2.78347694e-01,  6.87058723e-01, -1.23983653e+00,
         1.35186981e-01, -8.93011944e-01, -4.16253921e-01,
        -9.97933090e-01,  3.35020672e-01, -7.07106781e-01,
        -1.73014581e-01, -9.46761301e-01,  3.75114207e-01,
        -8.79823118e-01],
       [-1.96121513e+00, -1.45547966e+00, -1.90403467e-01,
        -6.48992045e-01, -6.26505951e-01, -4.16253921e-01,
        -9.97933090e-01,  8.55675750e-01, -7.07106781e-01,
        -9.00366347e-01, -9.46761301e-01, -7.09057343e-01,
        -8.79823118e-01],
       [ 3.94799280e-01,  6.87058723e-01, -1.90403467e-01,
         2.31614058e-02, -4.55180670e-01, -4.16253921e-01,
         1.01491918e+00,  9.85839519e-01, -7.07106781e-01,
         2.00904071e+00, -9.46761301e-01,  1.45928576e+00,
         1.17454219e+00],
       [ 8.43563930e-01, -1.45547966e+00,  8.59029595e-01,
         4.71263707e-01,  3.82409594e-01, -4.16253921e-01,
         1.01491918e+00,  4.21796519e-01, -7.07106781e-01,
         2.37271660e+00,  2.30515795e+00,  1.45928576e+00,
        -8.79823118e-01],
       [ 1.85328439e+00, -1.45547966e+00, -1.90403467e-01,
        -1.20911992e+00,  3.25301167e-01,  2.40237977e+00,
         1.01491918e+00, -8.79841175e-01, -7.07106781e-01,
        -9.00366347e-01, -9.46761301e-01,  3.75114207e-01,
        -8.79823118e-01],
       [ 1.18013742e+00, -1.45547966e+00, -1.90403467e-01,
         1.59151946e+00,  2.13373469e+00, -4.16253921e-01,
         1.01491918e+00,  3.13052104e-02, -7.07106781e-01,
        -1.73014581e-01, -9.46761301e-01, -7.09057343e-01,
        -8.79823118e-01],
       [ 3.94799280e-01,  6.87058723e-01,  8.59029595e-01,
        -9.85068771e-01,  1.33421671e+00, -4.16253921e-01,
         8.49304757e-03, -4.45961944e-01, -7.07106781e-01,
         3.10006836e+00,  2.30515795e+00,  2.54345731e+00,
         6.60950865e-01],
       [-1.66156532e-01, -1.45547966e+00,  8.59029595e-01,
        -8.88641693e-02,  3.06265025e-01, -4.16253921e-01,
         1.01491918e+00, -3.15798175e-01, -7.07106781e-01,
        -5.36690464e-01,  6.79198325e-01, -7.09057343e-01,
        -8.79823118e-01],
       [-1.62464164e+00,  6.87058723e-01,  8.59029595e-01,
         1.14341716e+00, -4.74216812e-01, -4.16253921e-01,
        -9.97933090e-01,  1.33294290e+00, -7.07106781e-01,
        -9.00366347e-01, -9.46761301e-01, -7.09057343e-01,
         1.17454219e+00],
       [ 8.43563930e-01,  6.87058723e-01, -1.90403467e-01,
        -8.88641693e-02, -3.21927673e-01, -4.16253921e-01,
        -9.97933090e-01, -1.85634405e-01, -7.07106781e-01,
         7.36175125e-01,  6.79198325e-01,  2.54345731e+00,
         1.17454219e+00],
       [ 3.94799280e-01, -1.45547966e+00,  8.59029595e-01,
        -1.76924780e+00,  1.68674679e-03, -4.16253921e-01,
         1.01491918e+00, -1.22694456e+00, -7.07106781e-01,
         8.82336002e-03,  6.79198325e-01, -7.09057343e-01,
        -8.79823118e-01],
       [-9.51494668e-01, -1.45547966e+00, -1.23983653e+00,
        -1.48918386e+00, -8.35903517e-01, -4.16253921e-01,
        -9.97933090e-01,  9.42451596e-01, -7.07106781e-01,
        -9.00366347e-01, -9.46761301e-01, -7.09057343e-01,
        -8.79823118e-01],
       [-1.17587699e+00,  6.87058723e-01,  8.59029595e-01,
        -6.48992045e-01, -1.50216850e+00, -4.16253921e-01,
        -9.97933090e-01, -2.72410252e-01,  1.41421356e+00,
         1.64536483e+00,  2.30515795e+00, -7.09057343e-01,
         6.60950865e-01],
       [-1.84902397e+00,  6.87058723e-01, -2.28926959e+00,
        -6.48992045e-01, -3.21927673e-01, -4.16253921e-01,
        -9.97933090e-01,  1.37633083e+00,  1.41421356e+00,
         2.55455454e+00,  6.79198325e-01, -7.09057343e-01,
         1.17454219e+00],
       [ 6.19181605e-01,  6.87058723e-01, -1.90403467e-01,
         4.71263707e-01, -1.19759022e+00, -4.16253921e-01,
         1.01491918e+00,  2.04856903e-01, -7.07106781e-01,
         1.82720277e+00,  6.79198325e-01, -7.09057343e-01,
        -8.79823118e-01],
       [ 1.62890207e+00,  6.87058723e-01, -2.28926959e+00,
         1.59151946e+00, -2.64819246e-01,  2.40237977e+00,
         1.01491918e+00, -8.36453252e-01, -7.07106781e-01,
        -8.09447376e-01,  6.79198325e-01,  3.75114207e-01,
        -8.79823118e-01],
       [-1.40025932e+00, -1.45547966e+00,  8.59029595e-01,
        -1.65722222e+00,  3.25301167e-01, -4.16253921e-01,
         1.01491918e+00, -1.22694456e+00, -7.07106781e-01,
        -3.54852523e-01,  6.79198325e-01, -7.09057343e-01,
        -8.79823118e-01],
       [-2.78347694e-01,  6.87058723e-01, -2.28926959e+00,
         1.14341716e+00,  9.53493865e-01,  2.40237977e+00,
        -9.97933090e-01,  1.20277913e+00, -7.07106781e-01,
         1.90661301e-01,  6.79198325e-01, -7.09057343e-01,
         1.17454219e+00],
       [-1.51245048e+00,  6.87058723e-01, -1.23983653e+00,
         1.91199769e-01, -8.54939660e-01, -4.16253921e-01,
        -9.97933090e-01, -7.93065329e-01, -7.07106781e-01,
        -9.00366347e-01,  6.79198325e-01, -7.09057343e-01,
         6.60950865e-01],
       [ 1.18013742e+00,  6.87058723e-01,  8.59029595e-01,
        -1.20911992e+00,  1.68674679e-03, -4.16253921e-01,
         1.01491918e+00,  3.35020672e-01, -7.07106781e-01,
        -3.54852523e-01, -9.46761301e-01,  1.45928576e+00,
         6.60950865e-01],
       [ 8.43563930e-01, -1.45547966e+00,  8.59029595e-01,
         1.03139158e+00, -7.44578227e-02, -4.16253921e-01,
        -9.97933090e-01,  1.61468980e-01,  1.41421356e+00,
         3.72499243e-01,  6.79198325e-01, -7.09057343e-01,
        -8.79823118e-01],
       [-9.51494668e-01,  6.87058723e-01, -1.90403467e-01,
         1.03139158e+00, -3.21927673e-01, -4.16253921e-01,
        -9.97933090e-01, -1.42246482e-01, -7.07106781e-01,
         2.37271660e+00,  6.79198325e-01, -7.09057343e-01,
        -8.79823118e-01],
       [ 1.40451974e+00,  6.87058723e-01,  8.59029595e-01,
         1.59151946e+00,  7.25060157e-01, -4.16253921e-01,
         1.01491918e+00, -1.83437548e+00,  1.41421356e+00,
         4.63418213e-01,  6.79198325e-01,  2.54345731e+00,
        -8.79823118e-01],
       [-1.28806816e+00, -1.45547966e+00, -1.90403467e-01,
        -5.36966470e-01, -6.64578236e-01, -4.16253921e-01,
        -9.97933090e-01,  6.38736134e-01, -7.07106781e-01,
        -7.18528405e-01,  6.79198325e-01, -7.09057343e-01,
        -8.79823118e-01],
       [ 1.06794625e+00,  6.87058723e-01, -2.28926959e+00,
         2.15164733e+00, -3.98072243e-01, -4.16253921e-01,
         1.01491918e+00,  2.04856903e-01, -7.07106781e-01,
        -3.54852523e-01,  6.79198325e-01, -7.09057343e-01,
         1.17454219e+00],
       [ 2.82608118e-01,  6.87058723e-01,  8.59029595e-01,
         1.03139158e+00,  5.34698733e-01, -4.16253921e-01,
         1.01491918e+00, -1.66082379e+00,  1.41421356e+00,
        -3.54852523e-01,  6.79198325e-01,  3.75114207e-01,
         6.60950865e-01]])

In [20]:
#restoring column names
heart_xtrain_sc=pd.DataFrame(heart_xtrain_sc,columns=heart_trainColumnNames)
heart_xtrain_sc.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,-0.390539,0.687059,0.859030,0.471264,0.972530,-0.416254,-0.997933,0.985840,1.414214,0.554337,-0.946761,-0.709057,1.174542
1,1.404520,-1.455480,-0.190403,1.143417,0.553735,-0.416254,-0.997933,0.942452,-0.707107,-0.900366,-0.946761,0.375114,-0.879823
2,-0.053965,0.687059,-1.239837,3.383929,0.667952,-0.416254,1.014919,1.940374,-0.707107,-0.900366,-0.946761,0.375114,1.174542
3,0.394799,-1.455480,0.859030,-0.088864,-0.969157,-0.416254,-0.997933,-0.836453,-0.707107,-0.354853,0.679198,-0.709057,-0.879823
4,0.619182,0.687059,0.859030,-0.088864,-0.797831,-0.416254,1.014919,-0.793065,1.414214,1.281689,0.679198,1.459286,1.174542

In [21]:
heart_xtest_sc=pd.DataFrame(heart_xtest_sc,columns=heart_trainColumnNames)
heart_xtest_sc.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,-0.390539,-1.455480,-0.190403,-0.648992,0.896385,-0.416254,1.014919,0.291633,-0.707107,-0.354853,-0.946761,-0.709057,-0.879823
1,-0.166157,0.687059,0.859030,-0.480954,0.648916,-0.416254,-0.997933,-2.398418,1.414214,0.918013,0.679198,1.459286,1.174542
2,-0.278348,0.687059,-1.239837,-0.648992,1.467470,-0.416254,-0.997933,0.942452,-0.707107,-0.718528,-0.946761,-0.709057,-0.879823
3,1.067946,0.687059,0.859030,0.751328,-0.683614,-0.416254,1.014919,-0.793065,-0.707107,0.918013,0.679198,1.459286,0.660951
4,0.619182,0.687059,0.859030,-0.817030,-0.340964,2.402380,-0.997933,0.421797,1.414214,0.372499,-0.946761,1.459286,1.174542

**Training and Testing**

Using Logistic Regression

In [22]:
lr = LogisticRegression()
lr.fit(heart_xtrain_sc, heart_ytrain)

LogisticRegression()

In [23]:
print('training:', lr.score(heart_xtrain_sc, heart_ytrain))
print('testing:', lr.score(heart_xtest, heart_ytest))

training: 0.8607594936708861
testing: 0.5666666666666667

Using Decesion tree

In [24]:
dt= DecisionTreeClassifier(random_state=25,ccp_alpha=0.001,max_features='sqrt',max_depth=6,min_samples_leaf=3)
dt.fit(heart_xtrain_sc, heart_ytrain)

DecisionTreeClassifier(ccp_alpha=0.001, max_depth=6, max_features='sqrt',
                       min_samples_leaf=3, random_state=25)

In [25]:
print('training:', dt.score(heart_xtrain_sc, heart_ytrain))
print('testing:', dt.score(heart_xtest, heart_ytest))

training: 0.9029535864978903
testing: 0.5



---

# Regression Model on Housing dataset

**Performing EDA:**

In [26]:
housing_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [27]:
housing_data.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [28]:
housing_data.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [29]:
housing_data.nunique()

price               219
area                284
bedrooms              6
bathrooms             4
stories               4
mainroad              2
guestroom             2
basement              2
hotwaterheating       2
airconditioning       2
parking               4
prefarea              2
furnishingstatus      3
dtype: int64

**Preprocessig the data:**

In [30]:
#Mapping the categorical feature
housing_data['mainroad'] = housing_data['mainroad'].map( {'yes': 1, 'no': 0} )
housing_data['guestroom'] = housing_data['guestroom'].map( {'yes': 1, 'no': 0} )
housing_data['basement'] = housing_data['basement'].map( {'yes': 1, 'no': 0} )
housing_data['hotwaterheating'] = housing_data['hotwaterheating'].map( {'yes': 1, 'no': 0} )
housing_data['airconditioning'] = housing_data['airconditioning'].map( {'yes': 1, 'no': 0} )
housing_data['prefarea'] = housing_data['prefarea'].map( {'yes': 1, 'no': 0} )
housing_data['furnishingstatus'] = housing_data['furnishingstatus'].map( {'furnished': 1, 'semi-furnished': 2, 'unfurnished': 3} )

housing_data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,1
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,1
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,2
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,1
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,1

In [31]:
#Feature Engineering
housing_data['total_rooms']=housing_data['bedrooms']+housing_data['bathrooms']+housing_data['guestroom']
housing_data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,total_rooms
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,1,6
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,1,8
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,2,5
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,1,6
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,1,6

In [34]:
housing_data=housing_data.drop('bedrooms',axis=1)
housing_data=housing_data.drop('bathrooms',axis=1)
housing_data=housing_data.drop('guestroom',axis=1)
housing_data.head()

,price,area,stories,mainroad,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,total_rooms
0,13300000,7420,3,1,0,0,1,2,1,1,6
1,12250000,8960,4,1,0,0,1,3,0,1,8
2,12250000,9960,2,1,1,0,0,2,1,2,5
3,12215000,7500,2,1,1,0,1,3,1,1,6
4,11410000,7420,2,1,1,0,1,2,0,1,6

**Train-Test Split:**

In [35]:
#splitting target and feature variable
house_x=housing_data.drop('price',axis=1)
house_y=housing_data['price']

In [36]:
#checking feature and target dataframes
house_x.head()

,area,stories,mainroad,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,total_rooms
0,7420,3,1,0,0,1,2,1,1,6
1,8960,4,1,0,0,1,3,0,1,8
2,9960,2,1,1,0,0,2,1,2,5
3,7500,2,1,1,0,1,3,1,1,6
4,7420,2,1,1,0,1,2,0,1,6

In [37]:
house_y.head()

0    13300000
1    12250000
2    12250000
3    12215000
4    11410000
Name: price, dtype: int64

In [38]:
house_xtrain, house_xtest, house_ytrain, house_ytest = train_test_split(house_x,house_y, test_size=0.2, random_state=25)

**Feature Scaling:**

In [39]:
sc= StandardScaler()

In [40]:
sc.fit(house_xtrain)

StandardScaler()

In [41]:
#preserving the column names
housing_trainColumnNames=house_xtrain.columns.values
housing_trainColumnNames

array(['area', 'stories', 'mainroad', 'basement', 'hotwaterheating',
       'airconditioning', 'parking', 'prefarea', 'furnishingstatus',
       'total_rooms'], dtype=object)

In [42]:
house_xtrain_sc= sc.fit_transform(house_xtrain)
house_xtrain_sc

array([[-0.26440419,  0.22636987,  0.41478068, ..., -0.57381904,
        -0.10189876,  0.4883782 ],
       [-0.01756526,  0.22636987,  0.41478068, ...,  1.74270968,
         1.20480302,  0.4883782 ],
       [-0.35190307,  0.22636987,  0.41478068, ..., -0.57381904,
        -0.10189876,  2.262819  ],
       ...,
       [-0.37861325,  0.22636987, -2.41091269, ..., -0.57381904,
         1.20480302,  0.4883782 ],
       [-0.3841395 , -0.94859756,  0.41478068, ..., -0.57381904,
        -0.10189876, -0.3988422 ],
       [ 0.01190804,  1.4013373 ,  0.41478068, ..., -0.57381904,
        -0.10189876, -0.3988422 ]])

In [43]:
house_xtest_sc= sc.transform(house_xtest)
house_xtest_sc

array([[ 1.56846698,  2.57630473,  0.41478068, ...,  1.74270968,
        -0.10189876,  2.262819  ],
       [ 0.6566366 ,  2.57630473,  0.41478068, ...,  1.74270968,
        -1.40860055, -0.3988422 ],
       [-0.94597438,  0.22636987, -2.41091269, ..., -0.57381904,
        -1.40860055, -0.3988422 ],
       ...,
       [-0.71110898, -0.94859756,  0.41478068, ..., -0.57381904,
         1.20480302, -1.2860626 ],
       [ 2.15793309, -0.94859756,  0.41478068, ..., -0.57381904,
        -0.10189876, -0.3988422 ],
       [-0.71110898, -0.94859756,  0.41478068, ..., -0.57381904,
         1.20480302, -1.2860626 ]])

In [44]:
#restoring column names
house_xtrain_sc=pd.DataFrame(house_xtrain_sc,columns=housing_trainColumnNames)
house_xtrain_sc.head()

,area,stories,mainroad,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,total_rooms
0,-0.264404,0.226370,0.414781,-0.727890,-0.230521,1.559830,0.348736,-0.573819,-0.101899,0.488378
1,-0.017565,0.226370,0.414781,1.373833,-0.230521,1.559830,-0.811943,1.742710,1.204803,0.488378
2,-0.351903,0.226370,0.414781,1.373833,-0.230521,-0.641095,1.509415,-0.573819,-0.101899,2.262819
3,1.292155,-0.948598,0.414781,-0.727890,-0.230521,-0.641095,1.509415,-0.573819,-0.101899,-0.398842
4,-1.056499,-0.948598,-2.410913,-0.727890,-0.230521,-0.641095,-0.811943,-0.573819,1.204803,-0.398842

In [45]:
house_xtest_sc=pd.DataFrame(house_xtest_sc,columns=housing_trainColumnNames)
house_xtest_sc.head()

,area,stories,mainroad,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,total_rooms
0,1.568467,2.576305,0.414781,-0.727890,-0.230521,1.559830,1.509415,1.742710,-0.101899,2.262819
1,0.656637,2.576305,0.414781,-0.727890,-0.230521,1.559830,2.670095,1.742710,-1.408601,-0.398842
2,-0.945974,0.226370,-2.410913,-0.727890,-0.230521,-0.641095,-0.811943,-0.573819,-1.408601,-0.398842
3,-0.789397,0.226370,0.414781,-0.727890,-0.230521,1.559830,-0.811943,-0.573819,-0.101899,0.488378
4,-0.932159,0.226370,0.414781,1.373833,-0.230521,-0.641095,-0.811943,-0.573819,-1.408601,-0.398842

**Training and Testing**

Using simple Linear Regression:

In [46]:
from sklearn.linear_model import LinearRegression
# Creating a Linear Regression model
model = LinearRegression()

# Training the model using the training data
model.fit(house_xtrain_sc, house_ytrain)

LinearRegression()

In [48]:
# Prediction on the test data
house_ypred = model.predict(house_xtest_sc)

In [49]:
#model Evaluation
# Calculate Mean Squared Error (MSE)
mse = mean_squared_error(house_ytest, house_ypred)

# Calculate R-squared (R2)
r2 = r2_score(house_ytest, house_ypred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

Mean Squared Error: 1130905189481.935
R-squared: 0.6320262116731992